# Generated by Django 2.1 on 2018-08-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_merge_20180816_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requestee_phone_2',
            field=models.CharField(max_length=10, null=True, verbose_name='Requestee Phone (2) - അപേക്ഷകന്\u200dറെ ഫോണ്\u200d നമ്പര്\u200d (2)'),
        ),
        migrations.AddField(
            model_name='request',
            name='requestee_phone_3',
            field=models.CharField(max_length=10, null=True, verbose_name='Requestee Phone (3)- അപേക്ഷകന്\u200dറെ ഫോണ്\u200d നമ്പര്\u200d (3)'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='latlng',
            field=models.CharField(blank=True, max_length=100, verbose_name='GPS Coordinates - GPS നിർദ്ദേശാങ്കങ്ങൾ '),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='latlng_accuracy',
            field=models.CharField(blank=True, max_length=100, verbose_name='GPS Accuracy - GPS കൃത്യത '),
        ),
    ]
